// 現行 TOYOTA 標準車型清單（依業務提供的清單為準）。
// 須與 prisma/seed.mjs 的 cars 清單保持一致。
export const STANDARD_CAR_MODELS = [
  "ALTIS",
  "ALTIS HV",
  "C CROSS",
  "C CROSS HV",
  "TOWN ACE",
  "TOWN ACE VAN",
  "VIOS",
  "Y CROSS",
  "ALPHARD HV",
  "ALPHARD PHV",
  "CAMRY",
  "CAMRY HV",
  "COROLLA SP",
  "CROWN HV",
  "GR 86",
  "GR YARIS",
  "HILUX",
  "LAND CRUISER",
  "PRIUS PHV",
  "RAV4",
  "RAV4 HV",
  "RAV4 PHV",
  "SIENNA HV",
  "SUPRA",
  "URBAN CRUISER",
  "bZ4X",
] as const;
